### ISSUE TITLE
custom dimensions and metrics

### ISSUE THREAD

**Issue by akash-pal** [sweetlabs/lib#1]
Google Analytics has changed custom variables to custom dimensions and metrics.
Is there a way to modify the current code

**Comment by simpleshadow** [comment]
@akash-pal Thanks for the note! 👍 Unfortunately, we are no longer maintaining this library, but you should be able to update [GAPokki.js](https://github.com/sweetlabs/lib/blob/master/GAPokki.js) to support Google's new analytics structure if you're still interested.

**Comment by akash-pal** [comment]
Thanks have used the Google analytics javascript files successfully in Cordova based apps.
